### ISSUE TITLE
Is it feasible to automatically generate bindings for all Qt classes?

### ISSUE THREAD

**Issue by AdrianEddy** [woboq/qmetaobject-rs#177]
This project is great, but it seems that manually wrapping all classes is somewhat limiting. Have you looked into integrating some automatic binding generation so that all Qt classes, structs, types etc can be used from Rust directly?

I know binding to a large and complex C++ code is not a trivial task, but it has been done before, for example [Qt for Python](https://doc.qt.io/qtforpython/shiboken6/index.html), [ritual](https://github.com/rust-qt/ritual)

Qt for Python seems to use [Shiboken](https://doc.qt.io/qtforpython/shiboken6/index.html) [(blog post)](https://www.qt.io/blog/2018/05/31/write-python-bindings) and maybe it could be possible to use something similar (or even modified Shiboken) for Rust too?

**Comment by ogoffart** [comment]
If you want to have automatically generated bindings, this project is not what it is.

The goal of this crate is to allow to create QML apps using rust, with an idiomatic rust API.
I do not believe that auto-generated bindings can provide an idiomatic rust API. (read the first section of my blog post for rationale:  https://woboq.com/blog/qmetaobject-from-rust.html )
Fortunately, the API surface required for QML is much smaller than the one required for QtWidgets.

Anyway, if you are looking for automatically generated bindings, i guess the crates from ritual is what you're looking for.
Shiboken could indeed help because it contains lots of information that would help to create bindings, but there is still lots of information missing to create rust bindings.

Since this is out of scope of this project, i'm closing this issue. thanks for your comment anyway.
