### ISSUE TITLE
docs.rs documentation is not avaiable

### ISSUE THREAD

**Issue by rnestler** [woboq/qmetaobject-rs#27]
The docs.rs project is unable to build the documentation for [qmetaobject](https://docs.rs/crate/qmetaobject/0.0.5): https://docs.rs/crate/qmetaobject/0.0.5/builds/135061.
Probably because Qt is not installed in the build environment there. Is there a way to get this working?

**Comment by ogoffart** [comment]
Is there a way to know that only the docs are being generated?  Maybe then we could do something dummy in build.rs

**Comment by ogoffart** [comment]
I don't know how to solve this problem. I guess installing Qt on the build environment is not an option. I wonder how other crates that have dependencies do it...

**Comment by jonas-schievink** [comment]
I've [left a comment](https://github.com/rust-lang/docs.rs/issues/23#issuecomment-493714813) on the docs.rs issue, maybe they'll provide the Qt libraries in the build environment.

You can detect that docs.rs is running by telling it to enable a special feature (see https://docs.rs/about). cc https://github.com/rust-lang/docs.rs/issues/147

**Comment by ogoffart** [comment]
Hopefully this will fix it: https://github.com/mystor/rust-cpp/pull/57

**Comment by ogoffart** [comment]
Well, that did not work :-(
First of all, i forgot to add a `[feature]` section in Cargo.toml for cpp_build and cpp_macros so the build of these crates is failling   https://docs.rs/crate/cpp_build/0.5.2/builds/165974 
(I did not know this was required)

Second: even then it would not work because it appears that the `[package.metadata.docs.rs]` in cpp_build is only interpreted when building the documentation for cpp_build.  But when building the documentation for the qmetaobject crate, it is not interpreted.  (As shown in the log of  https://docs.rs/crate/qmetaobject/0.1.0/builds/165979 ,  the build of cpp_build succeed while it should have failled)
While I wanted to get that automatically.
Maybe there are some environment variable that need to be tested instead, or some other way.

**Comment by ogoffart** [comment]
After more trial-error, i was able to get the documentation working: https://docs.rs/qmetaobject/0.1.2/qmetaobject/

**Comment by rnestler** [comment]
Awesome! Thanks a lot for your efforts @ogoffart
