### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by nrbnlulu** [woboq/qmetaobject-rs#280]
Is this project production ready?  
Why would one risk to use this instead C++ since this could be abandoned at any time?

**Comment by surban** [comment]
Yes, we are using it in production and it's working fine for us.

Of course there is always the risk of an open source project not being developed any further, but in this case it won't be much effort for you to maintain qmetaobject for your product. After all it is "just" a thin Rust wrapper around C++ classes. Once you understand how it works adding new functionality is quite easy. Unless the architecture of Qt changes dramatically no large modifications will be required to keep qmetaobject running.

The big benefit is that you can write your whole application in Rust instead of C++. We did the switch and never looked back. Although interfacing QML to Rust has become a bit more difficult (mostly due to missing documentation and examples), the benefits of using Rust over C++ for the rest of the application logic greatly outweighs this.

**Comment by nrbnlulu** [comment]
@surban Thanks for the response.  

Do you know who are the current maintainers?

Also do I need to commit to Qt's licensing for this project?

**Comment by surban** [comment]
I am also just a user and don't have more information.

Since you are linking Qt libraries you will have to fully comply with the Qt license.

**Comment by nrbnlulu** [comment]
seems like [CXX-qt](https://github.com/KDAB/cxx-qt) is better maintained

**Comment by ogoffart** [comment]
See also https://github.com/woboq/qmetaobject-rs/discussions/276
