### ISSUE TITLE
Add QML signal example

### ISSUE THREAD

**Issue by retro486** [woboq/qmetaobject-rs#73]
Sorry if this is obvious but I can’t seem to figure out how to make use of the signals in QML that get generated with the qt_signal! macro. Which scope or component do you target? How do you call it? Etc

**Comment by HiruNya** [comment]
I'm new to using this crate as well but is this what you wanted?
https://gist.github.com/HiruNya/33b71aea41394b4812b1b7fe4f05a5d7

For signals in qml, remember to put the `on` before the signal and ensure that the signal is camel case (not sure if this is necessary).
So in this case, `mySignal` was used by setting the `onMySignal` property.

**Comment by retro486** [comment]
That’s a good example, yes. Thanks! I supposed I thought the signal needed to be caught within the component I wanted to update not within the mode itself but QML can be modified from there by ID so that works. I was trying to debug my QAbstractListModel not rendering in a ListView so I wanted to use these to debug.

**Comment by HiruNya** [comment]
@retro486 Did you fix that problem?

I *may* have encountered the same problem, my SimpleListModel is not updating my GridView even though I call the notify signal. I sort of fixed it by [adding a signal handler](https://github.com/HiruNya/nyanko/blob/master/nyanko/qml/main.qml#L21) but I'm not sure why it works and if there is a better way.

**Comment by retro486** [comment]
@HiruNya Possibly the same issue. In my case I [added rowsAboutToBeInserted and rowsInserted ](https://gist.github.com/retro486/00662213ff22d4a303ac242c401b9691) but I had to move my collection modification to the QML, I couldn't figure out how to keep it all in Rust (which is preferable since I want as little application logic as possible in my QML). Here's the[ main.rs](https://gist.github.com/retro486/7c05ff2f12d500f6bb203c0001670874) for reference (it's my first Rust so I'll take any feedback). Using your way were you able to keep all the logic in Rust?

**Comment by HiruNya** [comment]
I got it working! I was using [`SimpleListModel`](https://docs.rs/qmetaobject/0.1.4/qmetaobject/listmodel/struct.SimpleListModel.html) and had to use its methods to change my list (I was replacing the whole list instead of using the `reset_data` method). Looking at the [source code](https://docs.rs/qmetaobject/0.1.4/src/qmetaobject/listmodel.rs.html#237) it seems that `begin_insert_rows`, `end_insert_rows`, `begin_remove_rows`, etc. were being used.

Since you are using [`QAbstractListModel`](https://docs.rs/qmetaobject/0.1.4/qmetaobject/listmodel/trait.QAbstractListModel.html), you can use [`begin_insert_rows`](https://docs.rs/qmetaobject/0.1.4/qmetaobject/listmodel/trait.QAbstractListModel.html#method.begin_insert_rows) and [`end_insert_rows`](https://docs.rs/qmetaobject/0.1.4/qmetaobject/listmodel/trait.QAbstractListModel.html#method.end_insert_rows) in your `add_dummy` function, without having to call it in QML. (There's an [example in the repo](https://github.com/woboq/qmetaobject-rs/blob/master/examples/todos/src/implementation.rs#L121) that does this)

**Comment by retro486** [comment]
Hm. I've updated my code to more closely match the source example but now I can't access my struct members from the QML in the delegate. My guess is I need to update[ my role_names function](https://github.com/retro486/task-progress/blob/master/src/main.rs#L91) to list the members I want to make accessible to QML?

**Comment by retro486** [comment]
I realized this discussion got off track from my original question so I'll bring it back full circle (I'm not sure what a better discussion forum for this is; the UT app developers Telegram?). This appears to be the condensed example I was looking for when using custom signals to work:

```rust
// main.rs
#[allow(non_snake_case)]
#[derive(QObject,Default)]
struct Tasks {
    // when my_count value is modified, the countChanged signal is tripped.
    my_count: qt_property!(usize; NOTIFY countChanged),
    countChanged: qt_signal!(),
}

fn main() {
    ...
    qml_register_type::<Tasks>(cstr!("Tasks"), 1, 0, cstr!("Tasks"));
    ...
}
```

```qml
// Main.qml
import Tasks 1.0

Tasks {
    id: tasks
    // reactions to custom signals defined in a model should be implemented in the model QML:
    onCountChanged: {
        // Do something when this signal is sent
    }
}
```
